apiVersion: apps/v1
kind: Deployment
metadata:
  name: spider-bot
  namespace: spider-bot
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: spider-bot
  template:
    metadata:
      labels:
        app: spider-bot
    spec:
      containers:
        - name: spider-bot
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
            - name: DATABASE_PATH
              value: "/data/tarantulas.sqlite"
          volumeMounts:
            - name: sqlite-data
              mountPath: /data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: sqlite-data
          persistentVolumeClaim:
            claimName: sqlite-data
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}